### ISSUE TITLE
The Uploader is giving me Incomplete status on some uploads when they work fine on the website

### ISSUE THREAD

**Issue by darinshepit** [Heroes-Profile/HeroesProfile.Uploader#24] opened 2021-09-23 08:19 UTC
I'm linking screenshots and two of the files that are throwing errors. I'm not sure why it doesn't work on the app, but I only started seeing this issue in the last few months. Normally, it would only say Incomplete for AI or custom games.

https://www.dropbox.com/sh/8xpkrdxps4pxrsj/AAAv-n9FzJeptav5ObSsOhNUa?dl=0

Thanks for your work!

**Comment by zeddicuzz** [comment] 2021-09-26 08:09
I have the same issue and have seen in previous issues it could be related to heroesprofile uploader running simultaneously with HOTS Logs Uploader. Disabling one of them at startup should be a workaround

**Comment by Zemill** [comment] 2021-09-27 11:43
This is a known issue we have been tryng to resolve.  So far the replication of the issue during testing has made it hard to determine an exact root cause

**Comment by SirDK** [comment] 2021-09-30 01:15
Here you go. Same issue https://dropmefiles.com/592312

**Comment by Zemill** [comment] 2022-04-08 12:54
Closing, root cause appears to be HotsLog uploader

**Closed by Zemill** 2022-04-08 12:54 UTC

**Comment by LuminairPrime** [comment] 2022-07-01 23:59
I can confirm this. Today I started using the HeroesProfile Uploader because I noticed the HOTSLogs uploader was failing to upload to HeroesProfile. The HeroesProfile uploader says "incomplete", so I made a copy of the replay, and the copy was uploaded properly and marked as a duplicate. But I don't know if the original upload from my client worked, just with a false incomplete error, or if someone else uploaded it.

I guess the workaround for now is to just not use the HOTSLogs uploader. Maybe there is a file locking problem. Ideally the error and log should say something about that.

**Comment by nightblade9** [comment] 2024-10-31 02:19
Same issue here. Not sure what HOTSLogs Uploader is. I have HOTS installed, and HeroesProfile Uploader, and that's it. I see 2/17 uploaded successfully, the rest as incomplete. Re-ran app, restarted my PC, etc. to no avail.

**Comment by Zemill** [comment] 2024-10-31 02:21
Post one of the incomplete files and I can take a look.  Also hit the show log button and see what the log says for the incomplete, if anything

**Comment by nightblade9** [comment] 2024-10-31 02:28
@Zemill ah, I tried the web loader and I was just about to email you. All 19 uploads repeatedly fail via the web upload.

The app loader logs don't have anything in them (app v2.4.1 started, started watching for new replays). Not sure why it's printing debug messages by default...

Anyway, here's the most recent file. I have 18 more, so let me know if you want me to zip and upload the entire bunch.

[2024-10-30 21.39.12 Sky Temple.zip](https://github.com/user-attachments/files/17581126/2024-10-30.21.39.12.Sky.Temple.zip)

**Comment by Zemill** [comment] 2024-10-31 11:48
> @Zemill ah, I tried the web loader and I was just about to email you. All 19 uploads repeatedly fail via the web upload.
> 
> The app loader logs don't have anything in them (app v2.4.1 started, started watching for new replays). Not sure why it's printing debug messages by default...
> 
> Anyway, here's the most recent file. I have 18 more, so let me know if you want me to zip and upload the entire bunch.
> 
> [2024-10-30 21.39.12 Sky Temple.zip](https://github.com/user-attachments/files/17581126/2024-10-30.21.39.12.Sky.Temple.zip)

AI games are not supported
